# Generated by Django 3.2.4 on 2021-07-23 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bonus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=50)),
                ('curso_pretendido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Matriculado', 'Matriclado')], max_length=100)),
                ('id_usuario', models.CharField(max_length=100)),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.bonus')),
            ],
        ),
    ]
