# Generated by Django 3.2.4 on 2021-07-23 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('indicado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicado',
            name='curso_pretendido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso'),
        ),
    ]
