# Generated by Django 3.2.4 on 2021-07-23 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_aluno', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=50)),
                ('id_usuario', models.CharField(blank=True, max_length=200)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
            ],
        ),
    ]
